// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace NoPreviewImage
{
    internal sealed partial class Vsix
    {
        public const string Id = "NoPreviewImage.34d50421-6219-48bd-b3a8-9398583d9d67";
        public const string Name = "NoPreviewImage";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Tony Hallett";
        public const string Tags = "";
    }
}
